Models/Master/City.cs
namespace Profixer.Models.Master
{
    public class City
    {
        public int CityID { get; set; }
        public int CUID { get; set; }
        public string CityName { get; set; }
        public bool IsActive { get; set; }
        public int CountryID { get; set; }
        public string CountryName { get; set; }
    }
}

Controllers/MasterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Profixer.Models.Account;
using Profixer.Models.Master;
using Profixer.Providers.Interfaces.Account;
using Profixer.Providers.Interfaces.Master;

namespace Profixer.Controllers;

public class MasterController : Controller
{
    private readonly ILogger<MasterController> _logger;
    private readonly IMaster _master;
    private readonly IAccount _account;

    public MasterController(ILogger<MasterController> logger, IMaster master, IAccount account)
    {
        _logger = logger;
        _master = master;
        _account = account;
    }


    [HttpGet]
    public async Task<IActionResult> Area()
    {
        return View();
    }

    public async Task<IActionResult> City(int countryID, int cityId, string userID)
    {
        ViewData["UserID"] = userID;
        ViewBag.UserID = userID;
        var cityList = await _master.CityList(countryID, cityId, userID);
        var dashboard = await _account.Dashboard(1);
        var dashboardDatas = new DashboardDatas();
        dashboardDatas.DashboardResponse = dashboard;
        dashboardDatas.CityResponse = cityList;

        var countryList = await _master.CountryList(countryID);
        ViewBag.Countries = new SelectList(countryList?.RtnData, "CountryID", "CountryName");

        if (countryID != 0 && cityId != 0)
        {
            ViewBag.CityName = cityList.RtnData.FirstOrDefault()?.CityName;
            ViewBag.CountryId = countryID;

            return PartialView("AddCity");
        }
        return PartialView("City", dashboardDatas);
    }

    [HttpPost]
    public async Task<IActionResult> AddorEditCity(City city)
    {
        var addCity = await _master.AddCity(city);
        return PartialView("AddCity");
    }
}

Views/Master/AddCity.cshtml
@{
   var s = @ViewBag.CityName;
   var m = @ViewBag.Countries;
}

<!-- Page Wrapper -->
<div id="addCityPartial">
   <div class="page-wrapper">
      <div class="content container-fluid">
         <!-- Page Header -->
         <div class="page-header">
            <div class="row">
               <div class="col-sm-12">
                  <h5 class="page-title">Add City</h5>
               </div>
            </div>
         </div>
         <!-- /Page Header -->
         <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
               <div class="card">
                  <div class="card-body">
                     <form>
                        <div class="row" id="VoucherModal">
                           <div class="col-xl-12">
                              <div class="form-group row">
                                 <label class="col-lg-12 col-form-label">City Name</label>
                                 <div class="col-lg-12">
                                    <input type="text" id="cityName" value="@s" class="form-control">
                                 </div>
                              </div>
                              <div class="form-group row">
                                 <label class="col-lg-12 col-form-label">Country</label>
                                 <div class="col-lg-12">
                                    <select id="countryid" class="form-control" name="countryID">
                                       @foreach (var country in ViewBag.Countries)
                                       {
                                          <option value="@country.Value">@country.Text</option>
                                       }
                                    </select>
                                 </div>
                              </div>

                              <div class="form-group row">
                                 <label class="col-lg-5 col-form-label">Status</label>
                                 <div style="text-align: center;" class="col-lg-7">
                                    <button class="btn btn-primary" href="#"
                                       style="background-color: #DAFFD4; border: none; color: green;"><b><i
                                             class="fa fa-check" aria-hidden="true"></i> Active</b></button> <button
                                       class="btn btn-primary"
                                       style="background-color: #F5F5F5; border: none; color: #444;"><b><i
                                             class="fa fa-times" aria-hidden="true"></i> Inactive</b></button>
                                 </div>

                              </div>

                              <div class="form-group row">
                                 <!-- <label class="col-lg-6 col-form-label">Status</label> -->
                                 @* <div style="text-align: left;" class="col-lg-12">

                                 </div> *@

                                 <div style="text-align: center;" class="col-lg-12">
                                    <a id="btnBacktoCityList" style="color:white" class="btn btn-primary"><b>&nbsp;
                                          &nbsp; Back &nbsp; &nbsp;</b></a>
                                    <a class="btn btn-primary" style="color:white" onclick="SaveCity()"><b>&nbsp;
                                          &nbsp; Add &nbsp; &nbsp;</b></a>
                                 </div>

                              </div>
                              <div class="text-center">
                                 <div class="popup111" id="popup111">
                                    <img class="rounded-circle" src="~/img/tick.png" alt="" style="width: 120px;">
                                    <h5 style="color:#F4891E;">Added Successfull!</h5>
                                    <p>Work with Profixer and Earn more...!!</p>
                                    <!-- <button type="submit" class="btn btn-primary" onclick="myFunction2()"><b>View</b></button> -->
                                    <a href="@Url.Action("City","Master")" class="btn btn-primary"><b>Ok</b></a>
                                 </div>
                              </div>

                              <!-- <div class="form-group row">!-->
                              <!-- <label class="col-lg-5 col-form-label">Customer Name</label> -->
                              <!-- <input class="col-lg-10 col-form-label" type="text" id="myInput" onkeyup="myFunction()" placeholder="Search" title="Type in a name">
                                    <div class="col-lg-2 text-center">
                                       <button type="submit" class="btn btn-primary" style="width:50px; height: 50px;"><b><a href="#" style="color:#fff;"><i class="fa fa-plus" aria-hidden="true"></i></a></b></button>
                                    </div>
                                 </div> -->

                              <!-- <div class="form-group row"> -->
                              <!-- <p>Customer Name / Mobile Number</p> -->
                              <!-- <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search" title="Type in a name"><button type="submit" class="btn btn-primary"><b><a href="#" style="color:#fff;"><i class="fa fa-plus" aria-hidden="true"></i> &nbsp; Add as New Customer</a></b></button> -->

                              <!-- <table id="myTable"> -->

                              <!-- <tr>
                                             <td colspan="2" style="text-align:center;"><button type="submit" class="btn btn-primary"><b><a href="add_ticket_details.html" style="color:#fff;"><i class="fa fa-plus" aria-hidden="true"></i> &nbsp; Add as New Customer</a></b></button></td>
                                          </tr> -->
                              <!--  <tr>
                                             <td><button class="btn buttons-pdf buttons-html5 btn-sm mr-1" style="color: #fff; border-color: #F4891E; background-color: #F4891E;" tabindex="0" aria-controls="" type="button" title="Add"><span><b>Mu</b></span></button></td>
                                             <td ><a href="#" style="color: #F4891E;">Muscat<br> <span style="color: #F4891E;">Oman</span></a></td>
                                             <td style="text-align:right;"><label class="switch">
  <input type="checkbox" checked>
  <span class="slider round"></span>
</label></td>
                                          </tr>
                                          <tr>
                                             <td><button class="btn buttons-pdf buttons-html5 btn-sm mr-1" style="color: #fff; border-color: #F4891E; background-color: #F4891E;" tabindex="0" aria-controls="" type="button" title="Add"><span><b>Se</b></span></button></td>
                                             <td><a href="#" style="color: #F4891E;">Seeb<br> <span style="color: #F4891E;">Oman</span></a></td>
                                             <td style="text-align:right;"><label class="switch">
  <input type="checkbox" checked>
  <span class="slider round"></span>
</label></td>
                                          </tr>
                                       </table>
                                    </div> -->
                           </div>

                        </div>

                     </form>
                  </div>
               </div>
            </div>
            <div class="col-md-3"></div>
         </div>
      </div>
      <br><br><br>
      <hr>
      <div class="footer-bottom">
         <div class="container">
            <p style="text-align:center;"><b>© 2023 All Rights Reserved. Developed and Maintained by <img
                     src="~/img/dbzeus.png" alt="Logo" style="width:70px;"></b></p>
         </div>
      </div>
   </div>
</div>

@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
}
@* <!-- /Page Wrapper -->
<!-- jQuery -->
<script src="~/js/jquery-3.2.1.min.js"></script>
<!-- Bootstrap Core JS -->
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<!-- Slimscroll JS -->
<script src="~/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="~/plugins/raphael/raphael.min.js"></script>
<script src="~/plugins/morris/morris.min.js"></script>
<script src="~/js/chart.morris.js"></script>
<!-- Custom JS -->
<script src="~/js/script.js"></script> *@

@* <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script> *@

<script>
   $(document).ready(function () {
      $('#btnBacktoCityList').on('click', function () {
         $('#lstCity').show();
         $('#addCityPartial').hide();
      });
      $('#ddlSevas').select2({ dropdownParent: $('#VoucherModal') });
   });
   function myFunction() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
         td = tr[i].getElementsByTagName("td")[0];
         if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
               tr[i].style.display = "";
            } else {
               tr[i].style.display = "none";
            }
         }
      }
   }
</script>

<script>
   function SaveCity() {
      var cityData = {
         CUID: $('#CUID').val(),
         CityName: $('#cityName').val(),
         IsActive: true,
         CountryID: $('#countryid').val(),
      };

      $.ajax({
         type: 'Post',
         url: './AddorEditCity',
         data: cityData,
         success: function (response) {
            $('#lstCity').show();
            $('#addCityPartial').hide();
         },
         error: function (response) {
            console.log('error');
         },
         complete: function (data) {
            console.log("complete")
            document.getElementById("popup111").style.display = "block";
         }
      });
      return false;
   }
</script>
<script>
   $ = function (id) {
      return document.getElementById(id);
   }

   var show = function (id) {
      $(id).style.display = 'block';
   }
   var hide = function (id) {
      $(id).style.display = 'none';
   }
</script>

Views/Master/City.cshtml
@model Profixer.Models.Account.DashboardDatas
@{
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
   * {
      box-sizing: border-box;
   }

   #myInput {
      background-image: url('~/css/searchicon.png');
      background-position: 10px 10px;
      background-repeat: no-repeat;
      width: 100%;
      font-size: 16px;
      padding: 12px 20px 12px 40px;
      border: 1px solid #ddd;
      margin-bottom: 12px;
   }

   #myTable {
      border-collapse: collapse;
      width: 100%;
      border: 1px solid #ddd;
      font-size: 18px;
   }

   #myTable th,
   #myTable td {
      text-align: left;
      padding: 10px;
      font-size: 15px;
   }

   #myTable tr {
      border-bottom: 1px solid #ddd;
   }

   #myTable tr.header,
   #myTable tr:hover {
      background-color: #f1f1f1;
   }
</style>
<!-- Page Wrapper -->
<div id="lstCity">
   <div class="page-wrapper">
      <div class="content container-fluid">
         <!-- Page Header -->
         <div class="page-header">
            <div class="row">
               <div class="col-sm-12">
                  <h5 class="page-title">City</h5>

               </div>
            </div>
         </div>
         <!-- /Page Header -->
         <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
               <div class="card">
                  <div class="card-body">
                     <form action="#">
                        <div class="row">
                           <div class="col-xl-12">

                              <div class="form-group row">
                                 <!-- <label class="col-lg-5 col-form-label">Customer Name</label> -->
                                 <input class="col-lg-9 col-form-label" type="text" id="myInput" onkeyup="myFunction()"
                                    placeholder="Search" title="Type in a name">
                                 <div class="col-lg-3 text-center">
                                    <button type="button" class="btn btn-primary" style="width:70px; height: 50px;"><b>
                                          <a id="btnAddCity" style="color:#fff;"><i class="fa fa-plus"
                                                aria-hidden="true"></i>
                                             Add</a></b></button>
                                 </div>
                              </div>

                              <div class="form-group row">
                                 <!-- <p>Customer Name / Mobile Number</p> -->
                                 <!-- <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search" title="Type in a name"><button type="submit" class="btn btn-primary"><b><a href="#" style="color:#fff;"><i class="fa fa-plus" aria-hidden="true"></i> &nbsp; Add as New Customer</a></b></button> -->

                                 <table id="myTable">

                                    <!-- <tr>
                                             <td colspan="2" style="text-align:center;"><button type="submit" class="btn btn-primary"><b><a href="add_ticket_details.html" style="color:#fff;"><i class="fa fa-plus" aria-hidden="true"></i> &nbsp; Add as New Customer</a></b></button></td>
                                          </tr> -->
                                    @foreach (var item in Model.CityResponse.RtnData)
                                    {
                                       @* var isChecked = item.IsActive ? "checked" : ""; *@
                                       <tr>
                                          <td><button class="btn buttons-pdf buttons-html5 btn-sm mr-1"
                                                style="color: #fff; border-color: #F4891E; background-color: #F4891E;"
                                                tabindex="0" aria-controls="" type="button"
                                                title="Add"><span><b>@item.CityName.Substring(0,2)</b></span></button></td>
                                          <td><a onclick="EditCityAjax(@item.CountryID, @item.CityID)"
                                                style="color: #F4891E;">@item.CityName<br> <span
                                                   style="color: #F4891E;">@item.CountryName</span></a></td>
                                          @* <td style="text-align:right;"><label class="switch">
                                       <input type="checkbox" @isChecked>
                                       <span class="slider round"></span>
                                       </label></td> *@
                                       </tr>
                                    }
                                 </table>
                              </div>
                           </div>

                        </div>

                     </form>
                  </div>
               </div>
            </div>
            <div class="col-md-3"></div>
         </div>
      </div>
      <br><br><br>
      <hr>
      <div class="footer-bottom">
         <div class="container">
            <p style="text-align:center;"><b>© 2023 All Rights Reserved. Developed and Maintained by <img
                     src="~/img/dbzeus.png" alt="Logo" style="width:70px;"></b></p>
         </div>
      </div>
   </div>
   <!-- /Page Wrapper -->
</div>
<!--Add Page-->
<div id="addCityPartial" style="display:none">
   @Html.Partial("AddCity")
</div>
<!--/Add Page-->
@section Scripts {
   @{
      await Html.RenderPartialAsync("_ValidationScriptsPartial");
   }
}
@* <!-- jQuery -->
<script src="~/js/jquery-3.2.1.min.js"></script>
<!-- Bootstrap Core JS -->
<script src="~/js/popper.min.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<!-- Slimscroll JS -->
<script src="~/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<script src="~/plugins/raphael/raphael.min.js"></script>
<script src="~/plugins/morris/morris.min.js"></script>
<script src="~/js/chart.morris.js"></script>
<!-- Custom JS -->
<script src="~/js/script.js"></script> *@

<script>
   function myFunction() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("myInput");
      filter = input.value.toUpperCase();
      table = document.getElementById("myTable");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
         td = tr[i].getElementsByTagName("td")[0];
         if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
               tr[i].style.display = "";
            } else {
               tr[i].style.display = "none";
            }
         }
      }
   }
</script>
<script>
   $(function () {
      $('#btnBacktoCityList').on('click', function () {
         $('#lstCity').show();
         $('#addCityPartial').hide();
      });
      $('#btnAddCity').on('click', function () {
         $('#lstCity').hide();
         $('#addCityPartial').show();
      });
   });

   function EditCityAjax(countryID, cityID) {
      $.ajax({
         type: 'GET',
         url: './City',
         data: { 'countryID': countryID, 'cityID': cityID },
         success: function (response) {
            console.log("success")
         },
         error: function (response) {
            console.log('error');
         },
         complete: function (data) {
            console.log("complete")
            $('#lstCity').hide();
            $('#addCityPartial').show();
         }
      });
      return false;
   }
</script>